---
title: "Week 2 Discussion Crypto Data"
output: html_notebook
---
# Install Packages
```{r}
#install.packages("tidyverse")
#install.packages("ggplot2")
#install.packages("gifski")
#install.packages("png")
install.packages("gganimate")
#install.packages("gapminder")
```


# Load Packages
```{r}
library(tidyverse)
library(ggplot2)
library(gifski)
library(png)
library(gganimate)
library(gapminder)
```

# Import Data
```{r}
crypto <- read.csv("CryptoData.csv", stringsAsFactors = FALSE)

crypto
```

# Visualization 1
```{r}
ggplot(gapminder, aes(Open, Close, size = Volume, colour = Symbol)) +
  geom_point(alpha = 0.7, show.legend = FALSE) +
  scale_size(range = c(2, 12)) +
  scale_x_log10() +
  facet_wrap(~Name) +
  # Here comes the gganimate specific bits
  labs(title = 'Date: {frame_time}', x = 'Open', y = 'Close') +
  transition_time(Date) +
  ease_aes('linear')
```




# Visualization 2

```{r}
ggplot(crypto, aes(x = Marketcap, y = Close)) + 
  geom_point(aes(colour = Symbol)) + 
  transition_states(Symbol,
                    transition_length = 2,
                    state_length = 1)
```

# Visualization 3
```{r}
p <- ggplot(
  crypto,
  aes(Close, Volume, group = Symbol, color = factor(Symbol))
  ) +
  geom_line() +
  scale_color_viridis_d() +
  labs(x = "Closing Price", y = "Volume") +
  theme(legend.position = "top")

p + transition_reveal(Date)



```

# Visualization 4
```{r}
plot <- crypto %>%
  ggplot() + 
    geom_point(aes(x = High, y = Low, col = Name, size = Marketcap), alpha = 0.8) + theme_minimal() + 
    theme(legend.position = "bottom") + guides(size = "none") + 
    labs(x = "Day's High" ,y = "Day's Low",  col = "") +
  transition_time(Date)

plot

```








